# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- bash: |
    sudo sed -i -- 's/#deb-src/deb-src/g' /etc/apt/sources.list && sudo sed -i -- 's/# deb-src/deb-src/g' /etc/apt/sources.list
    sudo apt-get update
    sudo apt-get build-dep -qq cppcheck
  displayName: 'Installing deps'
- bash: | 
    git clone --depth=10 https://github.com/noisymime/speeduino noisymime/speeduino
    git clone --depth=10 https://github.com/noisymime/cppcheck.git noisymime/cppcheck_github
  displayName: 'Cloning repos'
- bash: | 
    cd noisymime/cppcheck_github
    make
  displayName: 'Making cppcheck'
- bash: | 
    cd noisymime
    chmod +x speeduino/misra/check_misra.sh
    speeduino/misra/check_misra.sh -c "cppcheck_github"
  #This task is always an error if there are MISRA violations
  continueOnError: true
  displayName: 'Running Scan'

# Publish test results to Azure Pipelines
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/misra.xml' 
    #searchFolder: '$(System.DefaultWorkingDirectory)' # Optional
    #mergeTestResults: false # Optional
    #failTaskOnFailedTests: false # Optional
    #testRunTitle: # Optional
    #buildPlatform: # Optional
    #buildConfiguration: # Optional
    publishRunAttachments: true # Optional
